name: "lab-portainer"

services:
  ###### Portainer #########
  portainer:
    image: portainer/portainer-ee:latest
    container_name: lab.portainer
    restart: always
    depends_on:
      tailscale-portainer:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer/:/data
    environment:
      - PORTAINER_DISABLE_SSL=true
      - PORTAINER_HTTP_ONLY=1
    network_mode: service:tailscale-portainer

  ###### Tailscale for Portainer #########
  tailscale-portainer:
    image: tailscale/tailscale:latest
    container_name: lab.tailscale-portainer
    hostname: ${PORTAINER_HOSTNAME:-portainer}
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
      TS_ENABLE_HEALTH_CHECK: true
      TS_LOCAL_ADDR_PORT: 127.0.0.1:9002
      TS_SERVE_CONFIG: /etc/tailscale/serve.json
      TS_EXTRA_ARGS: --accept-dns=true
    volumes:
      - ./data/tailscale-portainer/state:/var/lib/tailscale
      - ./configs/tailscale/portainer/serve.json:/etc/tailscale/serve.json:ro
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
    restart: unless-stopped
